### ISSUE TITLE
building with crossbuilder fails

### ISSUE THREAD

**Issue by wdehoog** [ubports/unity-system-compositor#10]
Buidling unity-system-compositor with crossbuilder fails. See the log.
[crossbuild.log](https://github.com/ubports/unity-system-compositor/files/3971764/crossbuild.log)

**Comment by wdehoog** [comment]
I really don't understand how crossbuilder works but managed to get it going by changing the debian/control file.
```
diff --git a/debian/control b/debian/control
index 0620a82..007ece8 100644
--- a/debian/control
+++ b/debian/control
@@ -3,7 +3,7 @@ Section: x11
 Priority: optional
 Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
 Build-Depends: cmake,
-               cmake-data,
+               cmake-data:all,
                dbus,
                debhelper (>= 9),
                dh-python,
@@ -19,7 +19,7 @@ Build-Depends: cmake,
                libmirclient-dev (>= 0.26.0),
                libmirserver-dev (>= 0.26.0),
                pkg-config,
-               python3,
+               python3:native,
                python3-pil:native,
                python3-setuptools,
```

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-system-compositor/-/issues/10

Sorry for your inconvenience.
