### ISSUE TITLE
Inherited bug from cmake-extras

### ISSUE THREAD

**Issue by vanyasem** [ubports/unity-system-compositor#5]
This package fails to compiledue to this bug: https://github.com/ubports/cmake-extras/issues/2

Patching cmake-extras breaks the package and requires replacing `GTEST_BOTH_LIBRARIES` with `GMOCK_LIBRARIES` (or you need to remove it if it already links to GMOCK) in all affected `CMakeLists.txt`

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-system-compositor/-/issues/5

Sorry for your inconvenience.
